# Generated by Django 5.1.7 on 2025-03-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, upload_to='games/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
